### ISSUE TITLE
Power Rankings Not Updating

### ISSUE THREAD

**Issue by TOVIRAH** [dtcarls/ff_bot#14] opened 2017-10-31 22:34 UTC
We've installed the bot in a groupMe chat in our league and the power rankings haven't updated since week 4. I've forked the project so I could toy with it myself and see if I could debug the issue but just don't have the time to get into it right now with school. Anyone else noticed this? Any idea why? The code looks fine.

**Comment by dtcarls** [comment] 2017-11-01 03:33
Issue #1 was resolved on Sept. 22 if you installed on an earlier date it would not have the fix. If the problem is occurring after the fact please respond with your league ID and some screenshots in groupme if there are any.

Please also validate that power ranks _should_ be changing week to week with the following python
```
from espnff import League
league_id = 123456
year = 2017
league = League(league_id, year)
print(league.power_rankings(week=1))
print(league.power_rankings(week=2))
print(league.power_rankings(week=3))
<you get the idea>
```

**Comment by TOVIRAH** [comment] 2017-11-03 19:08
Thanks for the quick response. I will get back to you once I have a chance to test it out. The guy in our league that added the bot to the groupme hasn't responded, but we've had the bot since week 1, which would have been prior to 9/22. I've told him to remove it and readd it and see if it changes this coming week. 

Thanks again.

**Comment by raulvasquez** [comment] 2017-11-04 13:32
If you forked the repo you just need to submit a pull request to bring it online with this repo. If heroku is linked to your fork it should update without logging into group me

**Comment by dtcarls** [comment] 2017-12-18 18:34
@TOVIRAH closing issue. I will reopen if issue still occurring.

**Closed by dtcarls** 2017-12-18 18:34 UTC
